### ISSUE TITLE
AttributeError: 'RacecarGymEnv' object has no attribute '_cam_dist'

### ISSUE THREAD

**Issue by muupan** [bulletphysics/bullet3#2026]
`env.render(mode='rgb_array')` does not work for `RacecarGymEnv-v0`, while its metadata says it does. https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/bullet/racecarGymEnv.py#L24

Code:
```
import gym
import pybullet_envs

env = gym.make('RacecarBulletEnv-v0')
obs = env.reset()
env.render(mode='rgb_array')
```

Output:
```
$ python reproduce.py
pybullet build time: Dec 15 2018 18:48:13
current_dir=/Users/user/.local/share/virtualenvs/pybullet-playground-QMxmR86D/lib/python3.7/site-packages/pybullet_envs/bullet
init
options=
argv[0]=
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: Environment '<class 'pybullet_envs.bullet.racecarGymEnv.RacecarGymEnv'>' has deprecated methods '_step' and '_reset' rather than 'step' and 'reset'. Compatibility code invoked. Set _gym_disable_underscore_compat = True to disable this behavior.
Traceback (most recent call last):
  File "reproduce.py", line 7, in <module>
    env.render(mode='rgb_array')
  File "/Users/user/.local/share/virtualenvs/pybullet-playground-QMxmR86D/lib/python3.7/site-packages/gym/core.py", line 275, in render
    return self.env.render(mode, **kwargs)
  File "/Users/user/.local/share/virtualenvs/pybullet-playground-QMxmR86D/lib/python3.7/site-packages/gym/envs/registration.py", line 187, in render
    return env._render(mode, close=False)
  File "/Users/user/.local/share/virtualenvs/pybullet-playground-QMxmR86D/lib/python3.7/site-packages/pybullet_envs/bullet/racecarGymEnv.py", line 148, in _render
    distance=self._cam_dist,
AttributeError: 'RacecarGymEnv' object has no attribute '_cam_dist'
```

Environment
```
macOS High Sierra
Python 3.7.0
gym==0.10.9
pybullet==2.4.1
```

**Comment by erwincoumans** [comment]
Indeed, this environment needs more work, but the project relies on volunteers to improve things. If you care, please consider improving things and submit a pull request. Thanks!
