### ISSUE TITLE
 Not able to run example file `humanoidMotionCapture.py`, with pybullet 2.4.1.

### ISSUE THREAD

**Issue by RaymondDixon** [bulletphysics/bullet3#2081]
Trying to experiment with deepMimic example files. Not able to run example file `humanoidMotionCapture.py`, with pybullet 2.4.1. Getting below error.
 
```
Traceback (most recent call last):
  File "/Downloads/Dev/bullet3-master/examples/pybullet/examples/humanoidMotionCapture.py", line 365, in <module>
    timeStep=timeStep)
  File "/Downloads/Dev/bullet3-master/examples/pybullet/examples/pdControllerStable.py", line 43, in computePD
    axis = self._pb.getAxisDifferenceQuaternion(desiredPos,jointPos)
AttributeError: module 'pybullet' has no attribute 'getAxisDifferenceQuaternion'
```
 Please help.

**Comment by erwincoumans** [comment]
That file is newer than PyBullet 2.4.1, you will need PyBullet 2.4.2, uploaded a minute ago.
