### ISSUE TITLE
' pybullet.error: getLinkState failed ' when running multiple pybullet environment

### ISSUE THREAD

**Issue by waiyc** [bulletphysics/bullet3#2268]
Hi,

I was trying to implement [Keras WorldModel](https://github.com/AppliedDataSciencePartners/WorldModels) with the pybullet Kuka Grasp environment.
During the training of the controller in WorldModel, [the code](https://github.com/AppliedDataSciencePartners/WorldModels/blob/master/05_train_controller.py) will train the controller in parallel which multiple kuka environment will be create and run in parallel.

During the first run, multiple kuka grasp environment are created and able to run the training and close without any problem. However, when the training entered the second time the kuka grasp environment will encounter the following issues:

>Traceback (most recent call last):
  File "05_train_controller.py", line 526, in <module>
    main(args)
  File "05_train_controller.py", line 475, in main
    slave()
  File "05_train_controller.py", line 236, in slave
    new_model.make_env(current_env_name)
  File "/home/comp/catkin_keras_wm/src/model.py", line 94, in make_env
    self.env = make_env(env_name, seed=seed, render_mode=render_mode, model = model)
  File "/home/comp/catkin_keras_wm/src/env.py", line 22, in make_env
    env = KukaCamGymEnv(renders=True, isDiscrete=False, maxSteps=100000)
  File "/home/comp/catkin_keras_wm/bullet3/examples/pybullet/gym/pybullet_envs/bullet/kukaCamGymEnv.py", line 83, in __init__
Traceback (most recent call last):
  File "05_train_controller.py", line 526, in <module>
    self.reset()
  File "/home/comp/catkin_keras_wm/bullet3/examples/pybullet/gym/pybullet_envs/bullet/kukaCamGymEnv.py", line 126, in reset
Traceback (most recent call last):
  File "05_train_controller.py", line 526, in <module>
    self._observation = self.getExtendedObservation()
  File "/home/comp/catkin_keras_wm/bullet3/examples/pybullet/gym/pybullet_envs/bullet/kukaCamGymEnv.py", line 196, in getExtendedObservation
    com_p, com_o, _, _, _, _ = self._pybullet_client.getLinkState(self._kuka.kukaUid, 6, computeForwardKinematics=True)
pybullet.error: getLinkState failed.

I have modified the kukaCamGymEnv.py to use bulletClient based on the instructions mentioned in [issue:support multiple simulation](https://github.com/bulletphysics/bullet3/issues/1925) and [minitaur bullet client implementation](https://github.com/bulletphysics/bullet3/issues/1643#issuecomment-383072135) but the issue still remains.

**Comment by waiyc** [comment]
solved after changing the sequence of creating simulation environment.
