### ISSUE TITLE
deep mimic pybullet

### ISSUE THREAD

**Issue by bmahlbrand** [bulletphysics/bullet3#3123]
I followed the README and running the following seems to have no effect, no output, or GUI - could someone give advice on a quick start?

`python3 -m pybullet_envs.deep_mimic.testrl --arg_file run_humanoid3d_backflip_args.txt
`

**Comment by erwincoumans** [comment]
It should work after pip3 install pybullet etc, tested on Windows, Linux and Mac OSX. Perhaps try on a different computer? Without output there is nothing we can do, we cannot reproduce it.

**Comment by bmahlbrand** [comment]
Fair enough, managed to get it nearly running - but encountering the following problem after a few (could be one frame, not sure) frames render:

```
(base) PS C:\Users\$USER> python -m pybullet_envs.deep_mimic.testrl --arg_file run_humanoid3d_backflip_args.txt
parentdir= C:\Users\$USER\miniconda3\lib\site-packages
2020-10-26 22:46:32.864089: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
pybullet build time: Oct 26 2020 22:12:11
run_humanoid3d_backflip_args.txt
enable_draw= True
Initialization strategy: InitializationStrategy.RANDOM
starting thread 0
started testThreads thread 0 with threadHandle 00000000000005E4
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 456.43
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2070 with Max-Q Design/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000000994
MotionThreadFunc thread started
motion_file= data/motions/humanoid3d_backflip.txt
LOADING humanoid!
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: chest
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: neck
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_hip
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_ankle
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_shoulder
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_hip
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_ankle
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_shoulder
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: chest
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: neck
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_hip
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_ankle
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: right_shoulder
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_hip
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_ankle
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: urdfdom: no axis elemement for Joint, defaulting to (1,0,0) axis
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: left_shoulder
num_agents= 1

Num Agents: 1
len(agent_files)= 1
Agent 0: data/agents/ct_agent_humanoid_ppo.txt
2020-10-26 22:46:36.518084: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-26 22:46:36.520016: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-10-26 22:46:36.543553: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-10-26 22:46:36.543906: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: MSI
2020-10-26 22:46:36.544172: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: MSI
2020-10-26 22:46:36.544935: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-26 22:46:36.545877: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
state_offset= [ 0.5 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.  -0.
 -0. ]
state_scale= [0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. ]
2020-10-26 22:46:36.605034: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Traceback (most recent call last):
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable agent/resource/s_norm/std_ph from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/agent/resource/s_norm/std_ph)
         [[{{node agent/resource/s_norm/ReadVariableOp_4}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\$USER\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\$USER\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\testrl.py", line 97, in <module>
    world = build_world(args, True)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\testrl.py", line 68, in build_world
    world = RLWorld(env, arg_parser)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 20, in __init__
    self.build_agents()
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 75, in build_agents
    curr_agent = self._build_agent(i, curr_file)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 141, in _build_agent
    agent = AgentBuilder.build_agent(self, id, agent_file)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\agent_builder.py", line 18, in build_agent
    agent = PPOAgent(world, id, json_data)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\ppo_agent.py", line 32, in __init__
    super().__init__(world, id, json_data)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\pg_agent.py", line 43, in __init__
    super().__init__(world, id, json_data)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\tf_agent.py", line 22, in __init__
    super().__init__(world, id, json_data)
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\rl_agent.py", line 93, in __init__
    self._build_normalizers()
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\pg_agent.py", line 98, in _build_normalizers
    super()._build_normalizers()
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\tf_agent.py", line 106, in _build_normalizers
    self.s_norm.set_mean_std(-self.world.env.build_state_offset(self.id),
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py", line 36, in set_mean_std
    self._update_resource_tf()
  File "C:\Users\$USER\miniconda3\lib\site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py", line 76, in _update_resource_tf
    self.sess.run(self._update_op, feed_dict=feed)
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\$USER\miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable agent/resource/s_norm/std_ph from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/agent/resource/s_norm/std_ph)
         [[node agent/resource/s_norm/ReadVariableOp_4 (defined at \site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py:67) ]]

Errors may have originated from an input operation.
Input Source operations connected to node agent/resource/s_norm/ReadVariableOp_4:
 agent/resource/s_norm/std_ph (defined at \site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py:64)

Original stack trace for 'agent/resource/s_norm/ReadVariableOp_4':
  File "\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\site-packages\pybullet_envs\deep_mimic\testrl.py", line 97, in <module>
    world = build_world(args, True)
  File "\site-packages\pybullet_envs\deep_mimic\testrl.py", line 68, in build_world
    world = RLWorld(env, arg_parser)
  File "\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 20, in __init__
    self.build_agents()
  File "\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 75, in build_agents
    curr_agent = self._build_agent(i, curr_file)
  File "\site-packages\pybullet_envs\deep_mimic\learning\rl_world.py", line 141, in _build_agent
    agent = AgentBuilder.build_agent(self, id, agent_file)
  File "\site-packages\pybullet_envs\deep_mimic\learning\agent_builder.py", line 18, in build_agent
    agent = PPOAgent(world, id, json_data)
  File "\site-packages\pybullet_envs\deep_mimic\learning\ppo_agent.py", line 32, in __init__
    super().__init__(world, id, json_data)
  File "\site-packages\pybullet_envs\deep_mimic\learning\pg_agent.py", line 43, in __init__
    super().__init__(world, id, json_data)
  File "\site-packages\pybullet_envs\deep_mimic\learning\tf_agent.py", line 22, in __init__
    super().__init__(world, id, json_data)
  File "\site-packages\pybullet_envs\deep_mimic\learning\rl_agent.py", line 93, in __init__
    self._build_normalizers()
  File "\site-packages\pybullet_envs\deep_mimic\learning\pg_agent.py", line 98, in _build_normalizers
    super()._build_normalizers()
  File "\site-packages\pybullet_envs\deep_mimic\learning\tf_agent.py", line 100, in _build_normalizers
    self.s_norm = TFNormalizer(self.sess, 's_norm', self.get_state_size(),
  File "\site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py", line 18, in __init__
    self._build_resource_tf()
  File "\site-packages\pybullet_envs\deep_mimic\learning\tf_normalizer.py", line 67, in _build_resource_tf
    self.mean_tf.assign(self.mean_ph), self.std_tf.assign(self.std_ph))
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 882, in assign
    value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
  File "\site-packages\tensorflow\python\profiler\trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "\site-packages\tensorflow\python\framework\ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1992, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1393, in _dense_var_to_tensor
    return self.value()
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 565, in value
    return self._read_variable_op()
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 672, in _read_variable_op
    result = read_and_set_handle()
  File "\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 662, in read_and_set_handle
    result = gen_resource_variable_ops.read_variable_op(
  File "\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 483, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "\site-packages\tensorflow\python\framework\ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 0000000000000994 exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 00000000000005E4 exiting
Thread TERMINATED
```

**Comment by erwincoumans** [comment]
you need the right versions of all libs, and not the gpu version of tensorflow

**Comment by bmahlbrand** [comment]
thanks, so for future readers, the issue is using tensorflow 2.3 - 2.4
