### ISSUE TITLE
Live Plot from Matplotlib example 

### ISSUE THREAD

**Issue by rohit-kumar-j** [bulletphysics/bullet3#3159]
Hi! is there a way to draw a live plot from the pybullet.getJointStates(robot,<joint_index>) function similar to what is shown [here](https://pythonprogramming.net/live-graphs-matplotlib-tutorial/)? 
https://pythonprogramming.net/live-graphs-matplotlib-tutorial/

I've tried to use the testrender.py example from [here](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/examples/testrender.py) but I can't seem to get it to work.

This is the output from the console:

`>>> for _ in range (200):
...     p.stepSimulation()
...     jointAngle_1,x,y,z = p.getJointState(robot,1)
...     jointAngle_1
...     ani = animation.FuncAnimation(fig, animate, interval=1000)
...     plt.show()
...     time.sleep(1./240.)
... 
()
4.905359700362513e-05
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 353, in show
    return _backend_mod.show(*args, **kwargs)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3524, in show
    manager.show()  # Emits a warning for non-interactive backend.
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 446, in show
    self.canvas.draw()
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3agg.py", line 70, in draw
    backend_agg.FigureCanvasAgg.draw(self)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 1870, in draw
    self.canvas.draw_event(renderer)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1759, in draw_event
    self.callbacks.process(s, event)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 229, in process
    self.exception_handler(exc)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 81, in _exception_printer
    raise exc
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 959, in _start
    self._init_draw()
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1703, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/home/rkj/.local/lib/python3.6/site-packages/matplotlib/animation.py", line 1726, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "<stdin>", line 2, in animate
AttributeError: 'float' object has no attribute 'read'`

Warm Regards
Rohit

**Comment by rohit-kumar-j** [comment]
I found the solution for my noob question: **_This is a long answer and I will update it soon_**

What I did is: 1. ran the createMultiBodyLinks.py file with modifications (here it is):

```
import pybullet as p
import time
import pybullet_data
import numpy as np

p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.createCollisionShape(p.GEOM_PLANE)
p.createMultiBody(0, 0)

sphereRadius = 0.05
colSphereId = p.createCollisionShape(p.GEOM_SPHERE, radius=sphereRadius)
colBoxId = p.createCollisionShape(p.GEOM_BOX,
                                  halfExtents=[sphereRadius, sphereRadius, sphereRadius])

mass = 1
visualShapeId = -1

link_Masses = [1]
linkCollisionShapeIndices = [colBoxId]
linkVisualShapeIndices = [-1]
linkPositions = [[0, 0, 0.11]]
linkOrientations = [[0, 0, 0, 1]]
linkInertialFramePositions = [[0, 0, 0]]
linkInertialFrameOrientations = [[0, 0, 0, 1]]
indices = [0]
jointTypes = [p.JOINT_REVOLUTE]
axis = [[0, 0, 1]]

for i in range(2):
  for j in range(2):
    for k in range(2):
      basePosition = [
          1 + i * 5 * sphereRadius, 1 + j * 5 * sphereRadius, 1 + k * 5 * sphereRadius + 1
      ]
      baseOrientation = [0, 0, 0, 1]
      if (k & 2):
        sphereUid = p.createMultiBody(mass, colSphereId, visualShapeId, basePosition,
                                      baseOrientation)
      else:
        sphereUid = p.createMultiBody(mass,
                                      colBoxId,
                                      visualShapeId,
                                      basePosition,
                                      baseOrientation,
                                      linkMasses=link_Masses,
                                      linkCollisionShapeIndices=linkCollisionShapeIndices,
                                      linkVisualShapeIndices=linkVisualShapeIndices,
                                      linkPositions=linkPositions,
                                      linkOrientations=linkOrientations,
                                      linkInertialFramePositions=linkInertialFramePositions,
                                      linkInertialFrameOrientations=linkInertialFrameOrientations,
                                      linkParentIndices=indices,
                                      linkJointTypes=jointTypes,
                                      linkJointAxis=axis)

      p.changeDynamics(sphereUid,
                       -1,
                       spinningFriction=0.001,
                       rollingFriction=0.001,
                       linearDamping=0.0)
      for joint in range(p.getNumJoints(sphereUid)):
        p.setJointMotorControl2(sphereUid, joint, p.VELOCITY_CONTROL, targetVelocity=1, force=10)

p.setGravity(0, 0, -10)

print('\n')

for i in range(p.getNumJoints(sphereUid)):
  body = p.getBodyUniqueId(sphereUid, i)
  print('unique_id = ', body)
  state = p.getJointState(sphereUid, i)
  print('Joint States: ',state)
  info = p.getJointInfo(sphereUid, i)
  print('Joint Info: ',info,'\n')

p.setRealTimeSimulation(0)
p.startStateLogging(loggingType=p.STATE_LOGGING_GENERIC_ROBOT,fileName="./state_log.bin",objectUniqueIds=[1,2],logFlags=p.STATE_LOG_JOINT_TORQUES)
p.setRealTimeSimulation(1)

t=10
count=0
while (count<t):
  keys = p.getKeyboardEvents()
  print(keys,'data is currently being logged...')
  # print(p.getJointInfo(sphereUid, 1))
  count=count+1
  time.sleep(0.1)

print('data logging has ended...\n')

p.stopStateLogging(loggingId=1)
# p.setRealTimeSimulation(0)

stop_sim=1
count=0
while(count<stop_sim):
  keys =p.getKeyboardEvents()
  print('...')
  count=count+1
  time.sleep(0.1)

```

2. Once the data was logged in the 'state_log.bin' file, I was able to decode it using the provided code (dumpLog.py), again of course with my own modifications: 

```
import time
import math
from datetime import datetime
import struct
import sys
import os, fnmatch
import argparse
from time import sleep
import matplotlib.pyplot as plt 
import matplotlib.animation as animation

fileName = "state_log.bin"

def readLogFile(filename, verbose=True):
  f = open(filename, 'rb')

  print('Opened'),
  print(filename)

  keys = f.readline().decode('utf8').rstrip('\n').split(',')
  fmt = f.readline().decode('utf8').rstrip('\n')

  # The byte number of one record
  sz = struct.calcsize(fmt)
  # The type number of one record
  ncols = len(fmt)

  file=open('decoded_states.bin','a')

  if verbose:
    print('Keys:'),
    print(keys)
    print('Format:'),
    print(fmt)
    print('Size:'),
    print(sz)
    print('Columns:'),
    print(ncols)

  lenChunk = sz
  log = list()
  chunkIndex = 0
  while (lenChunk):
    check = f.read(2)
    lenChunk = 0
    if (check == b'\xaa\xbb'):
      mychunk = f.read(sz)
      lenChunk = len(mychunk)
      chunks = [mychunk]
      if verbose:
        print("num chunks:")
        print(len(chunks))

      for chunk in chunks:
        print("len(chunk)=", len(chunk), " sz = ", sz)
        if len(chunk) == sz:
          print("chunk #", chunkIndex)
          chunkIndex = chunkIndex + 1
          values = struct.unpack(fmt, chunk) 
          print('values :..... ',values )
          record = list()
          for i in range(1): # range(ncols)
            record.append(values[i])
            if verbose:
              # print("    ", keys[41], "=", values[41], ',', keys[1], '=', values[1])
              print( values[41], ',', values[1])
          torque=values[41]
          time_stamp=values[1]
          # print('values 41 ("t0")= ', time_stamp,'\n')
          file.write(str(torque)+','+str(time_stamp))
          file.write('\n')
          
          log.append(record)
    else:
      print("Error, expected aabb terminal")
      file.close()
  return log


numArgs = len(sys.argv)

print('Number of arguments:', numArgs, 'arguments.')
print('Argument List:', str(sys.argv))

if (numArgs > 1):
  fileName = sys.argv[1]

print("filename=")
print(fileName)

######################################

while True: 
    verbose_choice = input('Verbose? [y/n] ') 
    if verbose_choice == '' or not verbose_choice[0].lower() in ['y','n']:
      print('Please answer with "yes" or "no"!') 
    else:break 
if verbose_choice[0].lower() == 'y' : 
  print('\nreading from file...')
  verbose = True
  
if verbose_choice[0].lower() == 'n' : 
  print('\nNon verbose method...')
  verbose = False

######################################
plt.plot()
readLogFile(fileName, verbose)
```

3. This populated the 'decoded_states.bin' file, which I then easily decrypted using this code by [Sentdex](https://pythonprogramming.net/live-graphs-matplotlib-tutorial/):

```
import pybullet as p
import pybullet_data as p_data

import time
import matplotlib.pyplot as plt
import numpy as np  #to reshape for matplotlib
import os

import matplotlib.animation as animation 

fig = plt.figure()
ax1 = fig.add_subplot(1,1,1)

def animate(i):
    graph_data = open('solved_states.bin','r').read()
    lines = graph_data.split('\n')
    time_stamp = [] #time
    torque = [] #torque
    for line in lines:
        if len(line) > 1:
            x, y = line.split(',')
            time_stamp.append(float(y))
            torque.append(float(x))
    ax1.clear()
    ax1.plot(time_stamp, torque,color='r',label='Torque')
    ax1.set_title('Torque Vs Time')
    ax1.set_xlabel('Time')
    ax1.set_ylabel('Torque')
    ax1.legend(loc="upper right")

ani = animation.FuncAnimation(fig, animate, interval=1000)
plt.show()
```

This produced the following:

![image](https://user-images.githubusercontent.com/37873142/99940576-6b15d480-2d92-11eb-8e86-08269bc3054d.png)

Thereby logging it. Although I am now Integrating it all in one file so that it is all taken care of in one command ...Will update soon...
