### ISSUE TITLE
Shared memory connections to GUI_SERVER fail

### ISSUE THREAD

**Issue by binitshah** [bulletphysics/bullet3#3202]
Hello, when connecting two shared memory connections to a GUI_SERVER, I see `Connection terminated, couldn't get body info` and `pybullet.error: Not connected to physics server.` errors. I am running Ubuntu 20.04. Here are the scripts I've used:

1. server.py
```python
import time
import pybullet as p
import pybullet_data

p.connect(p.GUI_SERVER)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.loadURDF("plane.urdf")
p.setGravity(0, 0, -9.8066)

while True:
    p.stepSimulation()
    time.sleep(1 / 240)
```

2. client1.py
```python
import time
import pybullet as p
import pybullet_data

p.connect(p.SHARED_MEMORY)
p.setAdditionalSearchPath(pybullet_data.getDataPath())

rid = p.loadURDF("r2d2.urdf", [0, 0, 1], p.getQuaternionFromEuler([0, 0, 0]))

while True:
    p.stepSimulation()
    time.sleep(1 / 240)
```

3. client2.py
```python
import time
import pybullet as p
import pybullet_data

p.connect(p.SHARED_MEMORY)
# p.connect(p.SHARED_MEMORY, p.SHARED_MEMORY_KEY2)
p.setAdditionalSearchPath(pybullet_data.getDataPath())

rid = p.loadURDF("r2d2.urdf", [0, 0, 1], p.getQuaternionFromEuler([0, 0, 0]))

while True:
    p.stepSimulation()
    time.sleep(1 / 240)
```
---

The second connection fails regardless of whether the `SHARED_MEMORY_KEY2` key is used. Here's the error:
```bash
$ python3 client2.py 
pybullet build time: Oct  8 2020 00:11:27
PosixSharedMemory::releaseSharedMemory detached shared memory
Traceback (most recent call last):
  File "client2.py", line 13, in <module>
    p.stepSimulation()
pybullet.error: Not connected to physics server.
$ python3 client2.py 
pybullet build time: Oct  8 2020 00:11:27
Connection terminated, couldn't get body info
PosixSharedMemory::releaseSharedMemory detached shared memory
Traceback (most recent call last):
  File "client2.py", line 8, in <module>
    p.setAdditionalSearchPath(pybullet_data.getDataPath())
pybullet.error: Not connected to physics server.
$ python3 client2.py 
pybullet build time: Oct  8 2020 00:11:27
PosixSharedMemory::releaseSharedMemory detached shared memory
Traceback (most recent call last):
  File "client2.py", line 13, in <module>
    p.stepSimulation()
pybullet.error: Not connected to physics server.
```
It's possible to use the `setRealTimeSimulation` method in place of `stepSimulation` to step-side this error, but then it appears once more when `getCameraImage` and `setJointMotorControlArray` are introduced.

It would be helpful to be able to connect any arbitrary number of shared memory connections to a GUI_SERVER instance.

**Comment by erwincoumans** [comment]
There is only 1 connection allowed indeed. You can try getting the GRPC server to work, it allows more connections.
