### ISSUE TITLE
segmentation fault when connecting with GUI mode

### ISSUE THREAD

**Issue by Guptajakala** [bulletphysics/bullet3#4258]
Hi, when I connect pybullet with GUI mode, after a period of running (>20min), the program will run into seg fault. I traced the error with GDB and here shows the stack. However, if I use DIRECT mode, there is never such problem.

System: ubuntu 16.04
Pybullet version: 3.2.4

```
Thread 78 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffecebc7700 (LWP 23381)]
0x00007fff44f9787f in b3AlignedObjectArray<b3KeyboardEvent>::push_back (_Val=..., this=0x7fff031eaed0)
    at src/Bullet3Common/b3AlignedObjectArray.h:279
279	src/Bullet3Common/b3AlignedObjectArray.h: No such file or directory.
(gdb) bt
#0  0x00007fff44f9787f in b3AlignedObjectArray<b3KeyboardEvent>::push_back (_Val=..., this=0x7fff031eaed0)
    at src/Bullet3Common/b3AlignedObjectArray.h:279
#1  b3PluginManager::addEvents (this=0x7fff00f068b0, vrControllerEvents=vrControllerEvents@entry=0x7fff032d3300, 
    numVRControllerEvents=numVRControllerEvents@entry=0, keyEvents=<optimized out>, numKeyEvents=numKeyEvents@entry=1, 
    mouseEvents=0x0, numMouseEvents=numMouseEvents@entry=0) at examples/SharedMemory/b3PluginManager.cpp:171
#2  0x00007fff44f3708c in PhysicsServerCommandProcessor::stepSimulationRealTime (this=0x7fff01f58660, 
    dtInSec=9.9999999999999995e-07, vrControllerEvents=0x7fff032d3300, numVRControllerEvents=0, keyEvents=0x7ffe98c34220, 
    numKeyEvents=1, mouseEvents=0x0, numMouseEvents=0) at examples/SharedMemory/PhysicsServerCommandProcessor.cpp:15696
#3  0x00007fff44f7daee in MotionThreadFunc (userPtr=0x7fff032d27d8, lsMemory=<optimized out>)
    at examples/SharedMemory/PhysicsServerExample.cpp:432
#4  0x00007fff44ec9b90 in threadFunction (argument=0x7fff032d4260) at examples/MultiThreading/b3PosixThreadSupport.cpp:95
#5  0x00007ffff77ca6db in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff7b0361f in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) 
```

**Comment by erwincoumans** [comment]
It seems some GUI events are overflowing. Are some Keyboard, Mouse or VR controller events added?
