### ISSUE TITLE
Segmentation Fault when using IK_SDLS

### ISSUE THREAD

**Issue by SamNPowers** [bulletphysics/bullet3#4404]
I edited examples/pybullet/examples/ik_end_effector_orientation.py to use p.IK_SDLS, i.e.:

```
    jointPoses = p.calculateInverseKinematics(kukaId,
                                              kukaEndEffectorIndex,
                                              pos,
                                              orn,
                                              jointDamping=jd,
                                              solver=p.IK_SDLS)
```

This results in the following error when run using gdb:
```
Thread 3 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd817a700 (LWP 1353913)]
Jacobian::CalcDeltaThetasSDLS (this=this@entry=0x7fffd8179480) at examples/ThirdPartyLibs/BussIK/Jacobian.cpp:476
476	examples/ThirdPartyLibs/BussIK/Jacobian.cpp: No such file or directory.
(gdb) bt
#0  Jacobian::CalcDeltaThetasSDLS (this=this@entry=0x7fffd8179480) at examples/ThirdPartyLibs/BussIK/Jacobian.cpp:476
#1  0x00007ffff6b0c638 in IKTrajectoryHelper::computeIK (this=this@entry=0x7fffd06c8840, endEffectorTargetPosition=endEffectorTargetPosition@entry=0x7fffd8179a30, 
    endEffectorTargetOrientation=endEffectorTargetOrientation@entry=0x7fffd8179a50, endEffectorWorldPosition=endEffectorWorldPosition@entry=0x7fffd8179990, 
    endEffectorWorldOrientation=endEffectorWorldOrientation@entry=0x7fffd81799b0, q_current=0x7fffd0003950, numQ=numQ@entry=7, endEffectorIndex=6, 
    q_new=0x7fffd0005950, ikMethod=ikMethod@entry=10, linear_jacobian=0x7fffd018b060, angular_jacobian=0x7fffd0441090, jacobian_size=jacobian_size@entry=42, 
    dampIk=dampIk@entry=0x7fffd8179b70) at examples/SharedMemory/IKTrajectoryHelper.cpp:162
#2  0x00007ffff6b55347 in PhysicsServerCommandProcessor::processCalculateInverseKinematicsCommand (this=0x7fffe75d3330, clientCmd=..., serverStatusOut=..., 
    bufferServerToClient=<optimized out>, bufferSizeInBytes=<optimized out>) at examples/SharedMemory/PhysicsServerCommandProcessor.cpp:13706
#3  0x00007ffff6b69858 in PhysicsServerCommandProcessor::processCommand (this=0x7fffe75d3330, clientCmd=..., serverStatusOut=..., 
    bufferServerToClient=0x7fffd696f0a8 "BULLETd-v325MBD", <incomplete sequence \310>, bufferSizeInBytes=8388608)
    at examples/SharedMemory/PhysicsServerCommandProcessor.cpp:15250
#4  0x00007ffff6ba6051 in PhysicsServerSharedMemory::processClientCommands (this=0x7fffe7682eb0) at examples/SharedMemory/PhysicsServerSharedMemory.cpp:263
#5  0x00007ffff6b96b29 in MotionThreadFunc (userPtr=0x7fffe7682ec8, lsMemory=<optimized out>) at examples/SharedMemory/PhysicsServerExample.cpp:447
#6  0x00007ffff6ae2b90 in threadFunction (argument=0x7fffe6515990) at examples/MultiThreading/b3PosixThreadSupport.cpp:95
#7  0x00007ffff7e13609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7d38133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

I'm using pybullet 3.2.5, and have also seen the issue with 3.2.0, using python 3.8 on ubuntu.

I decided to try SDLS because I was seeing (in my own code, not the example above) that when I include a target_orientation, I get a significantly more inaccurate position than if I do not include it (e.g. distance of 0.42m vs 0.10m). The orientation is more accurate of course, but my use-case is more sensitive to position than orientation. Is there a recommended way to balance this trade-off? Or some orientation threshold I can set separately? (If this is not a quick question, and I should post a new issue, please let me know.)

Edit: Sorry had a typo in my code, for my last paragraph, the distances are 0.04m vs 1e-4m. 

Thanks!

**Comment by erwincoumans** [comment]
The method requires an iktree, and since there is no check for it, it crashes. I'll add the check to prevent a crash (but it won't compute IK). You can use the C++ Bullet Example Browser to run the SDLS example, see screenshot.

![image](https://user-images.githubusercontent.com/725468/221269570-32a8c282-5187-448d-9105-39d01c102139.png)
